version: '3.8'

services:

  web-backend:
    build: ./server
    image: server-image
    container_name: server-container
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password@db/mydblogin"

  web-frontend:
    build: ./client
    image: client-image
    container_name: client-container
    ports:
      - "4444:4444"
    depends_on:
      - web-backend

  db:
    container_name: tar-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: mydblogin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "1111:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "5555:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db